// Agent-made images: who may generate, where the file goes, and what comes back.
// The generator is stubbed, so nothing leaves the machine.
// Run with: npx tsx src/tests/image-routes.test.ts

import { mkdtempSync, existsSync, readdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import type { AddressInfo } from 'node:net';

const dataDir = mkdtempSync(path.join(tmpdir(), 'proof-image-routes-'));
process.env.DATABASE_PATH = path.join(dataDir, 'test.db');

function assertEqual<T>(actual: T, expected: T, message: string): void {
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a !== e) throw new Error(`${message}\n  expected ${e}\n  got      ${a}`);
}

async function run(): Promise<void> {
  const express = (await import('express')).default;
  const { createDocument, createDocumentAccessToken } = await import('../../server/db.ts');
  const { imageRoutes, serveGeneratedImage, setImageGeneratorForTests, getImageDir, ImageGenerationError } = await import('../../server/image-routes.ts');

  createDocument('imgdoc', '# Doc\n', {}, 'Doc');
  const editor = createDocumentAccessToken('imgdoc', 'editor').secret;
  const viewer = createDocumentAccessToken('imgdoc', 'viewer').secret;

  const prompts: string[] = [];
  const png = Buffer.from('89504e470d0a1a0a', 'hex');
  setImageGeneratorForTests(async (prompt, aspectRatio) => {
    prompts.push(`${aspectRatio} ${prompt}`);
    if (prompt === 'quota') throw new ImageGenerationError('limit: 0', 'IMAGE_QUOTA');
    return { data: png, mimeType: 'image/png' };
  });

  const app = express();
  app.use(express.json());
  app.use('/api', imageRoutes);
  app.get('/generated/:file', serveGeneratedImage);
  const server = app.listen(0);
  const base = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  const post = (body: unknown, token?: string) =>
    fetch(`${base}/api/live/image`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...(token ? { 'x-share-token': token } : {}) },
      body: JSON.stringify(body),
    });

  try {
    assertEqual((await post({ slug: 'imgdoc', prompt: 'An orange' })).status, 401, 'no token is refused');
    assertEqual((await post({ slug: 'imgdoc', prompt: 'An orange' }, viewer)).status, 403, 'a viewer cannot spend the quota');
    assertEqual((await post({ slug: 'imgdoc', prompt: '  ' }, editor)).status, 400, 'an empty prompt is refused');
    assertEqual(prompts.length, 0, 'nothing was generated for refused requests');

    const made = await post({ slug: 'imgdoc', prompt: 'An orange', aspectRatio: '16:9' }, editor);
    const body = (await made.json()) as { url: string; mimeType: string };
    assertEqual(made.status, 200, 'an editor can generate');
    assertEqual(/^\/generated\/[0-9a-f-]{36}\.png$/.test(body.url), true, 'the URL names a server-chosen file');
    assertEqual(prompts, ['16:9 An orange'], 'prompt and aspect ratio reach the generator');
    assertEqual(path.dirname(getImageDir()), dataDir, 'files live beside the database, on the volume');
    assertEqual(readdirSync(getImageDir()).length, 1, 'the file was written');

    const served = await fetch(base + body.url);
    assertEqual(served.status, 200, 'the image is served');
    assertEqual(Buffer.from(await served.arrayBuffer()).equals(png), true, 'with the generated bytes');
    assertEqual((await fetch(`${base}/generated/..%2Ftest.db`)).status, 404, 'only generated file names resolve');

    const fallback = await post({ slug: 'imgdoc', prompt: 'Another', aspectRatio: '7:3' }, editor);
    assertEqual(fallback.status, 200, 'an unknown aspect ratio falls back');
    assertEqual(prompts[1], '1:1 Another', 'to square');

    const quota = await post({ slug: 'imgdoc', prompt: 'quota' }, editor);
    assertEqual(quota.status, 429, 'a quota failure is reported as one');
    assertEqual(((await quota.json()) as { code: string }).code, 'IMAGE_QUOTA', 'with a code the client can read');
    assertEqual(existsSync(getImageDir()) && readdirSync(getImageDir()).length, 2, 'a failed generation writes nothing');
  } finally {
    server.close();
    setImageGeneratorForTests(null);
  }
  console.log('image-routes: all assertions passed');
}

run().then(() => process.exit(0)).catch((error) => {
  console.error(error);
  process.exit(1);
});
